import requests
from data.models import *

def get_user(user):
    url = f"https://cryptohack.org/api/user/{user}/"
    request = requests.get(url)
    assert request.status_code == 200, (
        f"Impossible d'obtenir les informations concernant {user}. "
        "Le nom d'utilisateur est-il bien correct ?"
    )
    json = request.json()
    assert 'user_count' in json, (
        f"Erreur {json['code']}: {json['message']}"
    )
    return json

CATEGORY_LINK = {
    "Introduction" : "https://cryptohack.org/challenges/introduction/",
    "General" : "https://cryptohack.org/challenges/general/",
    "Mathematics" : "https://cryptohack.org/challenges/maths/",
    "Symmetric Ciphers" : "https://cryptohack.org/challenges/aes/",
    "RSA" : "https://cryptohack.org/challenges/rsa/",
    "Diffie-Hellman" : "https://cryptohack.org/challenges/diffie-hellman/",
    "Elliptic Curves" : "https://cryptohack.org/challenges/ecc/",
    "Hash Functions" : "https://cryptohack.org/challenges/hashes/",
    "Crypto on the Web" : "https://cryptohack.org/challenges/web/",
    "Misc" : "https://cryptohack.org/challenges/misc/",
    "Post-Quantum" : "https://cryptohack.org/challenges/post-quantum/",
    "CTF Archive" : "https://cryptohack.org/challenges/ctf-archive/",
}

ALL_CHALLENGES = {
    "Introduction": [
        "Network Attacks",
        "Great Snakes",
        "Finding Flags",
    ],
    "General": [
        "CERTainly not",
        "Base64",
        "Modular Arithmetic 1",
        "Transparency",
        "Extended GCD",
        "XOR Properties",
        "SSH Keys",
        "Encoding Challenge",
        "Favourite byte",
        "ASCII",
        "Modular Arithmetic 2",
        "Modular Inverting",
        "Hex",
        "Greatest Common Divisor",
        "Privacy-Enhanced Mail?",
        "Lemur XOR",
        "Bytes and Big Integers",
        "XOR Starter",
        "You either know, XOR you don't",
    ],
    "Mathematics": [
        "Ellipse Curve Cryptography",
        "Broken RSA",
        "Legendre Symbol",
        "Find the Lattice",
        "Size and Basis",
        "Successive Powers",
        "Roll your Own",
        "Quadratic Residues",
        "No Way Back Home",
        "Adrien's Signs",
        "Gaussian Reduction",
        "Cofactor Cofantasy",
        "Gram Schmidt",
        "Backpack Cryptography",
        "Real Eisenstein",
        "What's a Lattice?",
        "Modular Square Root",
        "Modular Binomials",
        "Prime and Prejudice",
        "Unencryptable",
        "Vectors",
        "Chinese Remainder Theorem",
    ],
    "Symmetric Ciphers": [
        "Lazy CBC",
        "Dancing Queen",
        "Logon Zero",
        "Beatboxer",
        "ECB Oracle",
        "ECB CBC WTF",
        "Keyed Permutations",
        "Resisting Bruteforce",
        "Triple DES",
        "Diffusion through Permutation",
        "Forbidden Fruit",
        "Passwords as Keys",
        "Round Keys",
        "Structure of AES",
        "Stream of Consciousness",
        "Symmetry",
        "Paper Plane",
        "Oh SNAP",
        "Bringing It All Together",
        "CTRIME",
        "Bean Counter",
        "Confusion through Substitution",
        "Flipping Cookie",
        "Modes of Operation Starter",
    ],
    "RSA": [
        "Marin's Secrets",
        "RSA Backdoor Viability",
        "Salty",
        "Endless Emails",
        "Infinite Descent",
        "Let's Decrypt Again",
        "Square Eyes",
        "Inferius Prime",
        "Modulus Inutilis",
        "RSA Starter 4",
        "Monoprime",
        "RSA Starter 1",
        "Signing Server",
        "Blinding Light",
        "RSA Starter 5",
        "Bespoke Padding",
        "Fast Primes",
        "Manyprime",
        "Vote for Pedro",
        "Crossed Wires",
        "Factoring",
        "RSA Starter 2",
        "RSA Starter 3",
        "Null or Never",
        "Everything is Big",
        "Ron was Wrong, Whit is Right",
        "RSA Starter 6",
        "Let's Decrypt",
        "Everything is Still Big",
    ],
    "Diffie-Hellman": [
        "The Matrix Revolutions",
        "Diffie-Hellman Starter 5",
        "Parameter Injection",
        "Static Client",
        "Static Client 2",
        "The Matrix Reloaded",
        "Script Kiddie",
        "Diffie-Hellman Starter 4",
        "Diffie-Hellman Starter 3",
        "Diffie-Hellman Starter 1",
        "The Matrix",
        "Additive",
        "Export-grade",
        "Diffie-Hellman Starter 2",
    ],
    "Elliptic Curves": [
        "ProSign 3",
        "Montgomery's Ladder",
        "Smooth Criminal",
        "Curves and Logs",
        "Micro Transmissions",
        "No Random, No Bias",
        "Moving Problems",
        "Background Reading",
        "Scalar Multiplication",
        "Point Addition",
        "Real Curve Crypto",
        "Elliptic Nodes",
        "Efficient Exchange",
        "Curveball",
        "Digestive",
        "Exceptional Curves",
        "Edwards Goes Degenerate",
        "Point Negation",
        "Double and Broken",
    ],
    "Hash Functions": [
        "Twin Keys",
        "MDFlag",
        "Hash Stuffing",
        "PriMeD5",
        "MD0",
        "Collider",
        "No Difference",
        "Jack's Birthday Confusion",
        "Jack's Birthday Hash",
        "Invariant",
        "Mixed Up",
    ],
    "Crypto on the Web": [
        "RSA or HMAC? Part 2",
        "JSON in JSON",
        "Megalomaniac 2",
        "Saying Hello",
        "Token Appreciation",
        "Authenticated Handshake",
        "No Way JOSE",
        "Megalomaniac 3",
        "Sharks on the Wire",
        "Secure Protocols",
        "Megalomaniac 1",
        "Decrypting TLS 1.3",
        "JWT Secrets",
        "JWT Sessions",
        "RSA or HMAC?",
        "TLS Handshake",
        "Decrypting TLS 1.2",
    ],
    "Misc": [
        "No Leaks",
        "Nothing Up My Sleeve",
        "Trust Games",
        "Lo-Hi Card Game",
        "Bit by Bit",
        "Bruce Schneier's Password: Part 2",
        "LFSR Destroyer",
        "Bruce Schneier's Password",
        "Armory",
        "Gotta Go Fast",
        "Jeff's LFSR",
        "L-Win",
        "Toshi's Treasure",
        "RSA vs RNG",
    ],
    "Post-Quantum": [
        "LWE High Bits Message",
        "LWE Background",
        "LWE Intro",
        "From Private to Public Key LWE",
        "Noise Cheap",
        "LWE Low Bits Message",
        "Too Many Errors",
        "Nativity",
        "Missing Modulus",
        "Noise Free",
    ],
}
