import requests
from data.models import *

def get_user(user):
    url = f"https://cryptohack.org/api/user/{user}/"
    request = requests.get(url)
    assert request.status_code == 200, (
        f"Impossible d'obtenir les informations concernant {user}. "
        "Le nom d'utilisateur est-il bien correct ?"
    )
    json = request.json()
    assert 'user_count' in json, (
        f"Erreur {json['code']}: {json['message']}"
    )
    return json

CATEGORY_LINK = {
    "Introduction" : "https://cryptohack.org/challenges/introduction/",
    "General" : "https://cryptohack.org/challenges/general/",
    "Mathematics" : "https://cryptohack.org/challenges/maths/",
    "Symmetric Ciphers" : "https://cryptohack.org/challenges/aes/",
    "RSA" : "https://cryptohack.org/challenges/rsa/",
    "Diffie-Hellman" : "https://cryptohack.org/challenges/diffie-hellman/",
    "Elliptic Curves" : "https://cryptohack.org/challenges/ecc/",
    "Hash Functions" : "https://cryptohack.org/challenges/hashes/",
    "Crypto on the Web" : "https://cryptohack.org/challenges/web/",
    "Misc" : "https://cryptohack.org/challenges/misc/",
    "Post-Quantum" : "https://cryptohack.org/challenges/post-quantum/",
    "CTF Archive" : "https://cryptohack.org/challenges/ctf-archive/",
}

ALL_CHALLENGES = [
    "(Post-Quantum/Noise Free)",
    "(Post-Quantum/From Private to Public Key LWE)",
    "(Post-Quantum/LWE Low Bits Message)",
    "(Post-Quantum/LWE High Bits Message)",
    "(Post-Quantum/LWE Intro)",
    "(Post-Quantum/LWE Background)",
    "(Crypto on the Web/Authenticated Handshake)",
    "(Crypto on the Web/Decrypting TLS 1.3)",
    "(Crypto on the Web/Decrypting TLS 1.2)",
    "(RSA/Let's Decrypt Again)",
    "(Symmetric Ciphers/Oh SNAP)",
    "(Symmetric Ciphers/Forbidden Fruit)",
    "(Symmetric Ciphers/Paper Plane)",
    "(Misc/Armory)",
    "(Crypto on the Web/Saying Hello)",
    "(Crypto on the Web/TLS Handshake)",
    "(Crypto on the Web/Sharks on the Wire)",
    "(Crypto on the Web/Secure Protocols)",
    "(Diffie-Hellman/The Matrix Reloaded)",
    "(Symmetric Ciphers/Logon Zero)",
    "(Elliptic Curves/Exceptional Curves)",
    "(Elliptic Curves/ProSign 3)",
    "(Elliptic Curves/Moving Problems)",
    "(Elliptic Curves/Curveball)",
    "(Elliptic Curves/Double and Broken)",
    "(Elliptic Curves/Smooth Criminal)",
    "(Elliptic Curves/Montgomery's Ladder)",
    "(Elliptic Curves/Efficient Exchange)",
    "(Elliptic Curves/Curves and Logs)",
    "(Elliptic Curves/Scalar Multiplication)",
    "(Elliptic Curves/Point Addition)",
    "(Elliptic Curves/Point Negation)",
    "(Elliptic Curves/Background Reading)",
    "(Mathematics/Real Eisenstein)",
    "(Mathematics/Backpack Cryptography)",
    "(Hash Functions/Mixed Up)",
    "(Misc/L-Win)",
    "(Misc/Bruce Schneier's Password)",
    "(Misc/No Leaks)",
    "(Misc/Gotta Go Fast)",
    "(Hash Functions/MD0)",
    "(RSA/Vote for Pedro)",
    "(RSA/Let's Decrypt)",
    "(RSA/Null or Never)",
    "(RSA/Bespoke Padding)",
    "(RSA/Blinding Light)",
    "(RSA/Signing Server)",
    "(Hash Functions/PriMeD5)",
    "(Hash Functions/Hash Stuffing)",
    "(Crypto on the Web/RSA or HMAC? Part 2)",
    "(Diffie-Hellman/Static Client 2)",
    "(Crypto on the Web/JSON in JSON)",
    "(Crypto on the Web/RSA or HMAC?)",
    "(Symmetric Ciphers/Stream of Consciousness)",
    "(Symmetric Ciphers/ECB CBC WTF)",
    "(Symmetric Ciphers/CTRIME)",
    "(Symmetric Ciphers/Bean Counter)",
    "(Symmetric Ciphers/Symmetry)",
    "(Symmetric Ciphers/Triple DES)",
    "(Symmetric Ciphers/Lazy CBC)",
    "(Symmetric Ciphers/Flipping Cookie)",
    "(Hash Functions/Collider)",
    "(Diffie-Hellman/The Matrix)",
    "(Mathematics/Prime and Prejudice)",
    "(General/SSH Keys)",
    "(Mathematics/Adrien's Signs)",
    "(Mathematics/Broken RSA)",
    "(Mathematics/Find the Lattice)",
    "(Hash Functions/Jack's Birthday Hash)",
    "(Hash Functions/Jack's Birthday Confusion)",
    "(Mathematics/Gram Schmidt)",
    "(Diffie-Hellman/Static Client)",
    "(Diffie-Hellman/Export-grade)",
    "(Crypto on the Web/JWT Secrets)",
    "(Crypto on the Web/No Way JOSE)",
    "(Crypto on the Web/JWT Sessions)",
    "(Mathematics/Successive Powers)",
    "(Mathematics/Unencryptable)",
    "(Diffie-Hellman/Additive)",
    "(Diffie-Hellman/Parameter Injection)",
    "(Diffie-Hellman/Script Kiddie)",
    "(Diffie-Hellman/Diffie-Hellman Starter 2)",
    "(Diffie-Hellman/Diffie-Hellman Starter 5)",
    "(Diffie-Hellman/Diffie-Hellman Starter 4)",
    "(Diffie-Hellman/Diffie-Hellman Starter 3)",
    "(Diffie-Hellman/Diffie-Hellman Starter 1)",
    "(Symmetric Ciphers/ECB Oracle)",
    "(Symmetric Ciphers/Passwords as Keys)",
    "(Symmetric Ciphers/Modes of Operation Starter)",
    "(Symmetric Ciphers/Bringing It All Together)",
    "(Symmetric Ciphers/Diffusion through Permutation)",
    "(Symmetric Ciphers/Confusion through Substitution)",
    "(Symmetric Ciphers/Round Keys)",
    "(Symmetric Ciphers/Structure of AES)",
    "(Symmetric Ciphers/Keyed Permutations)",
    "(RSA/RSA Backdoor Viability)",
    "(RSA/Fast Primes)",
    "(RSA/Endless Emails)",
    "(Symmetric Ciphers/Resisting Bruteforce)",
    "(RSA/Ron was Wrong, Whit is Right)",
    "(Crypto on the Web/Token Appreciation)",
    "(RSA/Marin's Secrets)",
    "(RSA/Infinite Descent)",
    "(RSA/Modulus Inutilis)",
    "(RSA/Crossed Wires)",
    "(RSA/Everything is Still Big)",
    "(RSA/Everything is Big)",
    "(RSA/Salty)",
    "(RSA/Manyprime)",
    "(RSA/Square Eyes)",
    "(RSA/Inferius Prime)",
    "(RSA/Monoprime)",
    "(RSA/Factoring)",
    "(RSA/RSA Starter 6)",
    "(RSA/RSA Starter 5)",
    "(RSA/RSA Starter 4)",
    "(RSA/RSA Starter 3)",
    "(RSA/RSA Starter 2)",
    "(RSA/RSA Starter 1)",
    "(Mathematics/Modular Binomials)",
    "(Mathematics/What's a Lattice?)",
    "(Mathematics/Gaussian Reduction)",
    "(Mathematics/Size and Basis)",
    "(Mathematics/Vectors)",
    "(Mathematics/Chinese Remainder Theorem)",
    "(Mathematics/Modular Square Root)",
    "(Mathematics/Legendre Symbol)",
    "(Mathematics/Quadratic Residues)",
    "(General/Lemur XOR)",
    "(General/Transparency)",
    "(General/CERTainly not)",
    "(General/Privacy-Enhanced Mail?)",
    "(General/Modular Inverting)",
    "(General/Modular Arithmetic 2)",
    "(General/Modular Arithmetic 1)",
    "(General/Extended GCD)",
    "(General/Greatest Common Divisor)",
    "(General/You either know, XOR you don't)",
    "(General/Favourite byte)",
    "(General/XOR Properties)",
    "(General/XOR Starter)",
    "(General/Encoding Challenge)",
    "(General/Bytes and Big Integers)",
    "(General/Base64)",
    "(General/Hex)",
    "(General/ASCII)",
    "(Introduction/Network Attacks)",
    "(Introduction/Great Snakes)",
    "(Introduction/Finding Flags)",
    "(Diffie-Hellman/The Matrix Revolutions)",
    "(Post-Quantum/Too Many Errors)",
    "(Elliptic Curves/No Random, No Bias)",
    "(Elliptic Curves/Elliptic Nodes)",
    "(Elliptic Curves/Micro Transmissions)",
    "(Misc/Toshi's Treasure)",
    "(Misc/Bit by Bit)",
    "(Misc/Trust Games)",
    "(Misc/Nothing Up My Sleeve)",
    "(Misc/Lo-Hi Card Game)",
    "(Symmetric Ciphers/Dancing Queen)",
    "(Misc/Jeff's LFSR)",
    "(Elliptic Curves/Digestive)",
    "(Crypto on the Web/Megalomaniac 3)",
    "(Crypto on the Web/Megalomaniac 2)",
    "(Crypto on the Web/Megalomaniac 1)",
    "(Misc/RSA vs RNG)",
    "(Post-Quantum/Nativity)",
    "(Post-Quantum/Noise Cheap)",
    "(Post-Quantum/Missing Modulus)",
    "(CTF Archive/2020 (TETCTF))",
    "(Elliptic Curves/Real Curve Crypto)",
    "(Hash Functions/MDFlag)",
    "(Mathematics/No Way Back Home)",
    "(Symmetric Ciphers/Beatboxer)",
    "(Misc/LFSR Destroyer)",
    "(Mathematics/Roll your Own)",
    "(Misc/Bruce Schneier's Password: Part 2)",
    "(Mathematics/Cofactor Cofantasy)",
    "(Hash Functions/Invariant)",
    "(Hash Functions/No Difference)",
    "(Hash Functions/Twin Keys)",
    "(Elliptic Curves/Edwards Goes Degenerate)",
    "(Mathematics/Ellipse Curve Cryptography)",
    "(CTF Archive/GLP420 (HackTM CTF))",
]
