import requests
from data.models import *

def get_user(user):
    url = f"https://cryptohack.org/api/user/{user}/"
    request = requests.get(url)
    assert request.status_code == 200, (
        f"Impossible d'obtenir les informations concernant {user}. "
        "Le nom d'utilisateur est-il bien correct ?"
    )
    json = request.json()
    assert 'user_count' in json, (
        f"Erreur {json['code']}: {json['message']}"
    )
    return json

CATEGORY_LINK = {
    "Introduction" : "https://cryptohack.org/challenges/introduction/",
    "General" : "https://cryptohack.org/challenges/general/",
    "Mathematics" : "https://cryptohack.org/challenges/maths/",
    "Symmetric Ciphers" : "https://cryptohack.org/challenges/aes/",
    "RSA" : "https://cryptohack.org/challenges/rsa/",
    "Diffie-Hellman" : "https://cryptohack.org/challenges/diffie-hellman/",
    "Elliptic Curves" : "https://cryptohack.org/challenges/ecc/",
    "Hash Functions" : "https://cryptohack.org/challenges/hashes/",
    "Crypto on the Web" : "https://cryptohack.org/challenges/web/",
    "Misc" : "https://cryptohack.org/challenges/misc/",
    "Post-Quantum" : "https://cryptohack.org/challenges/post-quantum/",
    "CTF Archive" : "https://cryptohack.org/challenges/ctf-archive/",
}

ALL_CHALLENGES = {
    "(Post-Quantum/Noise Free)": "Noise Free",
    "(Post-Quantum/From Private to Public Key LWE)": "From Private to Public Key LWE",
    "(Post-Quantum/LWE Low Bits Message)": "LWE Low Bits Message",
    "(Post-Quantum/LWE High Bits Message)": "LWE High Bits Message",
    "(Post-Quantum/LWE Intro)": "LWE Intro",
    "(Post-Quantum/LWE Background)": "LWE Background",
    "(Crypto on the Web/Authenticated Handshake)": "Authenticated Handshake",
    "(Crypto on the Web/Decrypting TLS 1.3)": "Decrypting TLS 1.3",
    "(Crypto on the Web/Decrypting TLS 1.2)": "Decrypting TLS 1.2",
    "(RSA/Let's Decrypt Again)": "Let's Decrypt Again",
    "(Symmetric Ciphers/Oh SNAP)": "Oh SNAP",
    "(Symmetric Ciphers/Forbidden Fruit)": "Forbidden Fruit",
    "(Symmetric Ciphers/Paper Plane)": "Paper Plane",
    "(Misc/Armory)": "Armory",
    "(Crypto on the Web/Saying Hello)": "Saying Hello",
    "(Crypto on the Web/TLS Handshake)": "TLS Handshake",
    "(Crypto on the Web/Sharks on the Wire)": "Sharks on the Wire",
    "(Crypto on the Web/Secure Protocols)": "Secure Protocols",
    "(Diffie-Hellman/The Matrix Reloaded)": "The Matrix Reloaded",
    "(Symmetric Ciphers/Logon Zero)": "Logon Zero",
    "(Elliptic Curves/Exceptional Curves)": "Exceptional Curves",
    "(Elliptic Curves/ProSign 3)": "ProSign 3",
    "(Elliptic Curves/Moving Problems)": "Moving Problems",
    "(Elliptic Curves/Curveball)": "Curveball",
    "(Elliptic Curves/Double and Broken)": "Double and Broken",
    "(Elliptic Curves/Smooth Criminal)": "Smooth Criminal",
    "(Elliptic Curves/Montgomery's Ladder)": "Montgomery's Ladder",
    "(Elliptic Curves/Efficient Exchange)": "Efficient Exchange",
    "(Elliptic Curves/Curves and Logs)": "Curves and Logs",
    "(Elliptic Curves/Scalar Multiplication)": "Scalar Multiplication",
    "(Elliptic Curves/Point Addition)": "Point Addition",
    "(Elliptic Curves/Point Negation)": "Point Negation",
    "(Elliptic Curves/Background Reading)": "Background Reading",
    "(Mathematics/Real Eisenstein)": "Real Eisenstein",
    "(Mathematics/Backpack Cryptography)": "Backpack Cryptography",
    "(Hash Functions/Mixed Up)": "Mixed Up",
    "(Misc/L-Win)": "L-Win",
    "(Misc/Bruce Schneier's Password)": "Bruce Schneier's Password",
    "(Misc/No Leaks)": "No Leaks",
    "(Misc/Gotta Go Fast)": "Gotta Go Fast",
    "(Hash Functions/MD0)": "MD0",
    "(RSA/Vote for Pedro)": "Vote for Pedro",
    "(RSA/Let's Decrypt)": "Let's Decrypt",
    "(RSA/Null or Never)": "Null or Never",
    "(RSA/Bespoke Padding)": "Bespoke Padding",
    "(RSA/Blinding Light)": "Blinding Light",
    "(RSA/Signing Server)": "Signing Server",
    "(Hash Functions/PriMeD5)": "PriMeD5",
    "(Hash Functions/Hash Stuffing)": "Hash Stuffing",
    "(Crypto on the Web/RSA or HMAC? Part 2)": "RSA or HMAC? Part 2",
    "(Diffie-Hellman/Static Client 2)": "Static Client 2",
    "(Crypto on the Web/JSON in JSON)": "JSON in JSON",
    "(Crypto on the Web/RSA or HMAC?)": "RSA or HMAC?",
    "(Symmetric Ciphers/Stream of Consciousness)": "Stream of Consciousness",
    "(Symmetric Ciphers/ECB CBC WTF)": "ECB CBC WTF",
    "(Symmetric Ciphers/CTRIME)": "CTRIME",
    "(Symmetric Ciphers/Bean Counter)": "Bean Counter",
    "(Symmetric Ciphers/Symmetry)": "Symmetry",
    "(Symmetric Ciphers/Triple DES)": "Triple DES",
    "(Symmetric Ciphers/Lazy CBC)": "Lazy CBC",
    "(Symmetric Ciphers/Flipping Cookie)": "Flipping Cookie",
    "(Hash Functions/Collider)": "Collider",
    "(Diffie-Hellman/The Matrix)": "The Matrix",
    "(Mathematics/Prime and Prejudice)": "Prime and Prejudice",
    "(General/SSH Keys)": "SSH Keys",
    "(Mathematics/Adrien's Signs)": "Adrien's Signs",
    "(Mathematics/Broken RSA)": "Broken RSA",
    "(Mathematics/Find the Lattice)": "Find the Lattice",
    "(Hash Functions/Jack's Birthday Hash)": "Jack's Birthday Hash",
    "(Hash Functions/Jack's Birthday Confusion)": "Jack's Birthday Confusion",
    "(Mathematics/Gram Schmidt)": "Gram Schmidt",
    "(Diffie-Hellman/Static Client)": "Static Client",
    "(Diffie-Hellman/Export-grade)": "Export-grade",
    "(Crypto on the Web/JWT Secrets)": "JWT Secrets",
    "(Crypto on the Web/No Way JOSE)": "No Way JOSE",
    "(Crypto on the Web/JWT Sessions)": "JWT Sessions",
    "(Mathematics/Successive Powers)": "Successive Powers",
    "(Mathematics/Unencryptable)": "Unencryptable",
    "(Diffie-Hellman/Additive)": "Additive",
    "(Diffie-Hellman/Parameter Injection)": "Parameter Injection",
    "(Diffie-Hellman/Script Kiddie)": "Script Kiddie",
    "(Diffie-Hellman/Diffie-Hellman Starter 2)": "Diffie-Hellman Starter 2",
    "(Diffie-Hellman/Diffie-Hellman Starter 5)": "Diffie-Hellman Starter 5",
    "(Diffie-Hellman/Diffie-Hellman Starter 4)": "Diffie-Hellman Starter 4",
    "(Diffie-Hellman/Diffie-Hellman Starter 3)": "Diffie-Hellman Starter 3",
    "(Diffie-Hellman/Diffie-Hellman Starter 1)": "Diffie-Hellman Starter 1",
    "(Symmetric Ciphers/ECB Oracle)": "ECB Oracle",
    "(Symmetric Ciphers/Passwords as Keys)": "Passwords as Keys",
    "(Symmetric Ciphers/Modes of Operation Starter)": "Modes of Operation Starter",
    "(Symmetric Ciphers/Bringing It All Together)": "Bringing It All Together",
    "(Symmetric Ciphers/Diffusion through Permutation)": "Diffusion through Permutation",
    "(Symmetric Ciphers/Confusion through Substitution)": "Confusion through Substitution",
    "(Symmetric Ciphers/Round Keys)": "Round Keys",
    "(Symmetric Ciphers/Structure of AES)": "Structure of AES",
    "(Symmetric Ciphers/Keyed Permutations)": "Keyed Permutations",
    "(RSA/RSA Backdoor Viability)": "RSA Backdoor Viability",
    "(RSA/Fast Primes)": "Fast Primes",
    "(RSA/Endless Emails)": "Endless Emails",
    "(Symmetric Ciphers/Resisting Bruteforce)": "Resisting Bruteforce",
    "(RSA/Ron was Wrong, Whit is Right)": "Ron was Wrong, Whit is Right",
    "(Crypto on the Web/Token Appreciation)": "Token Appreciation",
    "(RSA/Marin's Secrets)": "Marin's Secrets",
    "(RSA/Infinite Descent)": "Infinite Descent",
    "(RSA/Modulus Inutilis)": "Modulus Inutilis",
    "(RSA/Crossed Wires)": "Crossed Wires",
    "(RSA/Everything is Still Big)": "Everything is Still Big",
    "(RSA/Everything is Big)": "Everything is Big",
    "(RSA/Salty)": "Salty",
    "(RSA/Manyprime)": "Manyprime",
    "(RSA/Square Eyes)": "Square Eyes",
    "(RSA/Inferius Prime)": "Inferius Prime",
    "(RSA/Monoprime)": "Monoprime",
    "(RSA/Factoring)": "Factoring",
    "(RSA/RSA Starter 6)": "RSA Starter 6",
    "(RSA/RSA Starter 5)": "RSA Starter 5",
    "(RSA/RSA Starter 4)": "RSA Starter 4",
    "(RSA/RSA Starter 3)": "RSA Starter 3",
    "(RSA/RSA Starter 2)": "RSA Starter 2",
    "(RSA/RSA Starter 1)": "RSA Starter 1",
    "(Mathematics/Modular Binomials)": "Modular Binomials",
    "(Mathematics/What's a Lattice?)": "What's a Lattice?",
    "(Mathematics/Gaussian Reduction)": "Gaussian Reduction",
    "(Mathematics/Size and Basis)": "Size and Basis",
    "(Mathematics/Vectors)": "Vectors",
    "(Mathematics/Chinese Remainder Theorem)": "Chinese Remainder Theorem",
    "(Mathematics/Modular Square Root)": "Modular Square Root",
    "(Mathematics/Legendre Symbol)": "Legendre Symbol",
    "(Mathematics/Quadratic Residues)": "Quadratic Residues",
    "(General/Lemur XOR)": "Lemur XOR",
    "(General/Transparency)": "Transparency",
    "(General/CERTainly not)": "CERTainly not",
    "(General/Privacy-Enhanced Mail?)": "Privacy-Enhanced Mail?",
    "(General/Modular Inverting)": "Modular Inverting",
    "(General/Modular Arithmetic 2)": "Modular Arithmetic 2",
    "(General/Modular Arithmetic 1)": "Modular Arithmetic 1",
    "(General/Extended GCD)": "Extended GCD",
    "(General/Greatest Common Divisor)": "Greatest Common Divisor",
    "(General/You either know, XOR you don't)": "You either know, XOR you don't",
    "(General/Favourite byte)": "Favourite byte",
    "(General/XOR Properties)": "XOR Properties",
    "(General/XOR Starter)": "XOR Starter",
    "(General/Encoding Challenge)": "Encoding Challenge",
    "(General/Bytes and Big Integers)": "Bytes and Big Integers",
    "(General/Base64)": "Base64",
    "(General/Hex)": "Hex",
    "(General/ASCII)": "ASCII",
    "(Introduction/Network Attacks)": "Network Attacks",
    "(Introduction/Great Snakes)": "Great Snakes",
    "(Introduction/Finding Flags)": "Finding Flags",
    "(Diffie-Hellman/The Matrix Revolutions)": "The Matrix Revolutions",
    "(Post-Quantum/Too Many Errors)": "Too Many Errors",
    "(Elliptic Curves/No Random, No Bias)": "No Random, No Bias",
    "(Elliptic Curves/Elliptic Nodes)": "Elliptic Nodes",
    "(Elliptic Curves/Micro Transmissions)": "Micro Transmissions",
    "(Misc/Toshi's Treasure)": "Toshi's Treasure",
    "(Misc/Bit by Bit)": "Bit by Bit",
    "(Misc/Trust Games)": "Trust Games",
    "(Misc/Nothing Up My Sleeve)": "Nothing Up My Sleeve",
    "(Misc/Lo-Hi Card Game)": "Lo-Hi Card Game",
    "(Symmetric Ciphers/Dancing Queen)": "Dancing Queen",
    "(Misc/Jeff's LFSR)": "Jeff's LFSR",
    "(Elliptic Curves/Digestive)": "Digestive",
    "(Crypto on the Web/Megalomaniac 3)": "Megalomaniac 3",
    "(Crypto on the Web/Megalomaniac 2)": "Megalomaniac 2",
    "(Crypto on the Web/Megalomaniac 1)": "Megalomaniac 1",
    "(Misc/RSA vs RNG)": "RSA vs RNG",
    "(Post-Quantum/Nativity)": "Nativity",
    "(Post-Quantum/Noise Cheap)": "Noise Cheap",
    "(Post-Quantum/Missing Modulus)": "Missing Modulus",
    "(CTF Archive/2020 (TETCTF))": "2020 (TETCTF)",
    "(Elliptic Curves/Real Curve Crypto)": "Real Curve Crypto",
    "(Hash Functions/MDFlag)": "MDFlag",
    "(Mathematics/No Way Back Home)": "No Way Back Home",
    "(Symmetric Ciphers/Beatboxer)": "Beatboxer",
    "(Misc/LFSR Destroyer)": "LFSR Destroyer",
    "(Mathematics/Roll your Own)": "Roll your Own",
    "(Misc/Bruce Schneier's Password: Part 2)": "Bruce Schneier's Password: Part 2",
    "(Mathematics/Cofactor Cofantasy)": "Cofactor Cofantasy",
    "(Hash Functions/Invariant)": "Invariant",
    "(Hash Functions/No Difference)": "No Difference",
    "(Hash Functions/Twin Keys)": "Twin Keys",
    "(Elliptic Curves/Edwards Goes Degenerate)": "Edwards Goes Degenerate",
    "(Mathematics/Ellipse Curve Cryptography)": "Ellipse Curve Cryptography",
    "(CTF Archive/GLP420 (HackTM CTF))": "GLP420 (HackTM CTF)",
}
